export const PRICING_TIERS = [
    {
        name: 'Free Starter',
        price: 0,
        period: 'forever',
        description: 'Try our builder and see the magic',
        features: [
            'Create 1 resume',
            '3 Basic Templates',
            'Basic AI suggestions (2 tokens)',
            'Standard PDF export',
        ],
        limitations: [
            'No DOCX export',
            'No Premium Templates',
            'No Interview Simulator',
            'Watermarked export',
        ],
        cta: 'Try for Free',
        ctaLink: '/auth/signup?tier=free',
        highlighted: false,
    },
    {
        name: 'Basic',
        price: 4.99,
        period: 'one-time',
        description: 'Perfect for a single professional resume',
        features: [
            'Create 1 professional resume',
            'All Standard Templates',
            'Basic AI improvements (5 tokens)',
            'Clean PDF & DOCX export',
            'Limited Skills Gap Analysis (1/mo)',
        ],
        limitations: [
            'No Premium Templates',
            'No Interview Simulator',
            'No Career Roadmap',
        ],
        cta: 'Get Started',
        ctaLink: '/auth/signup?tier=basic',
        highlighted: false,
        paddlePriceId: process.env.NEXT_PUBLIC_PADDLE_BASIC_PRICE_ID
    },
    {
        name: 'Interview Prep',
        price: 9.99,
        period: 'one-time',
        description: 'Master your interviews with AI-powered practice',
        features: [
            'Unlimited AI Interview Simulations',
            'Real-time Answer Feedback',
            'Industry-specific Question Banks',
            'Behavioral & Technical Mock Interviews',
            'Performance Analytics Dashboard',
        ],
        limitations: [
            'No Resume Builder Access',
            'No Document Exports',
            'No Career Roadmap',
        ],
        cta: 'Start Practicing',
        ctaLink: '/auth/signup?tier=interview',
        highlighted: false,
        paddlePriceId: process.env.NEXT_PUBLIC_PADDLE_INTERVIEW_PRICE_ID
    },
    {
        name: 'Pro Career Hub',
        price: 14.99,
        period: 'one-time',
        description: 'Strategic tools for active job seekers',
        features: [
            'Create up to 5 documents',
            'All Standard & Creative Templates',
            'Intermediate AI usage (30 tokens)',
            'Full Skills Gap Analysis suite',
            'Personalized AI Interview Prep',
            'PDF & DOCX export',
        ],
        limitations: [
            'No Career Roadmap',
        ],
        cta: 'Level Up My Career',
        ctaLink: '/auth/signup?tier=starter',
        highlighted: true,
        badge: 'Most Popular',
        paddlePriceId: process.env.NEXT_PUBLIC_PADDLE_STARTER_PRICE_ID
    },
    {
        name: 'Executive Elite',
        price: 29.99,
        period: 'month',
        yearlyPrice: 249.99,
        description: 'Comprehensive brand management and growth',
        features: [
            'Unlimited documents & exports',
            'Access to all Premium Templates',
            'Unlimited AI Resume improvements',
            'Unlimited Interview Simulations',
            '5-Year Visual Career Roadmap',
            'Priority AI generation speed',
            'Long-form career content generation',
        ],
        limitations: [],
        cta: 'Get Elite Access',
        ctaLink: '/auth/signup?tier=premium',
        highlighted: false,
        paddlePriceId: process.env.NEXT_PUBLIC_PADDLE_PREMIUM_PRICE_ID
    },
]
